source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-archives"
gem "jekyll-email-protect"
gem "jekyll-feed"
gem "jekyll-imagemagick"
gem "jekyll-minifier"
gem "jekyll-paginate-v2"
gem "jekyll/scholar"
gem "jekyll-sitemap"
gem "jekyll-toc"
gem "jemoji"
gem "nokogiri"
gem "webrick"
